# Model Evaluation

This notebook evaluates the model performance across different sampling techniques and datasets.

## Import Libraries and Load Results

In [18]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

import sys
sys.path.append('../../')
from utils.eval_plots import EvalPlots
from utils.model_performance_report import ModelPerformanceReport

## Load models and Data

In [19]:
holdout = pd.read_parquet('../../data/holdout_data.parquet')
oot = pd.read_parquet('../../data/oot_data.parquet')
train = pd.read_parquet('../../data/train_data.parquet')
metadata_columns = ['trans_date_trans_time','gender','street']

train_X = train.drop(columns=['is_fraud']+metadata_columns)
train_y = train['is_fraud']

holdout_X = holdout.drop(columns=['is_fraud']+metadata_columns)[train_X.columns]
holdout_y = holdout['is_fraud']

oot_X = oot.drop(columns=['is_fraud']+metadata_columns)[train_X.columns]
oot_y = oot['is_fraud']

In [20]:
score_standard_model = pd.read_pickle('../../models/score_balanced_model.pkl')
score_balanced_model = pd.read_pickle('../../models/score_balanced_model.pkl')
score_balanced_parameter_model = pd.read_pickle('../../models/score_balanced_parameter_model.pkl')

In [21]:
report_class = ModelPerformanceReport(train_X,train_y,holdout_X,holdout_y,oot_X,oot_y)
eval_plots = EvalPlots()

# Compare models

Show how model stability changes between the 3 model versions and explain why

In [22]:
# Compare models results

# Generate reports for standard model
standard_report = report_class.produce_report(score_standard_model)
standard_pr_auc_report = report_class.produce_pr_auc_report(score_standard_model)

# Generate reports for balanced model
balanced_report = report_class.produce_report(score_balanced_model)
balanced_pr_auc_report = report_class.produce_pr_auc_report(score_balanced_model)

# Generate reports for balanced parameter tuned model
balanced_param_report = report_class.produce_report(score_balanced_parameter_model)
balanced_param_pr_auc_report = report_class.produce_pr_auc_report(score_balanced_parameter_model)

# Combine reports into a single DataFrame for comparison
comparison_df = pd.concat([standard_report.add_suffix('_standard'), balanced_report.add_suffix('_balanced'), balanced_param_report.add_suffix('_tuned')], axis=1)
#comparison_df.columns = ['Standard Model', 'Balanced Model', 'Balanced Parameter Tuned Model']

# Display the comparison DataFrame
comparison_df

[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200

,train_standard,holdout_standard,oot_standard,train_balanced,holdout_balanced,oot_balanced,train_tuned,holdout_tuned,oot_tuned
accuracy,0.995753,0.994909,0.991392,0.995753,0.994909,0.991392,0.995753,0.994909,0.991392
precision,0.575478,0.533258,0.294857,0.575478,0.533258,0.294857,0.575478,0.533258,0.294857
recall,1.000000,0.928665,0.897614,1.000000,0.928665,0.897614,1.000000,0.928665,0.897614
f1,0.730544,0.677489,0.443898,0.730544,0.677489,0.443898,0.730544,0.677489,0.443898

## Compare Performance Metrics

In [23]:
# Compare models results

# Generate reports for standard model
standard_report = report_class.produce_report(score_standard_model)
standard_pr_auc_report = report_class.produce_pr_auc_report(score_standard_model)

# Generate reports for balanced model
balanced_report = report_class.produce_report(score_balanced_model)
balanced_pr_auc_report = report_class.produce_pr_auc_report(score_balanced_model)

# Generate reports for balanced parameter tuned model
balanced_param_report = report_class.produce_report(score_balanced_parameter_model)
balanced_param_pr_auc_report = report_class.produce_pr_auc_report(score_balanced_parameter_model)

# Combine reports into a single DataFrame for comparison
comparison_df = pd.concat([standard_report.add_suffix('_standard'), balanced_report.add_suffix('_balanced'), balanced_param_report.add_suffix('_tuned')], axis=1)
#comparison_df.columns = ['Standard Model', 'Balanced Model', 'Balanced Parameter Tuned Model']

# Display the comparison DataFrame
comparison_df

[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200

,train_standard,holdout_standard,oot_standard,train_balanced,holdout_balanced,oot_balanced,train_tuned,holdout_tuned,oot_tuned
accuracy,0.995753,0.994909,0.991392,0.995753,0.994909,0.991392,0.995753,0.994909,0.991392
precision,0.575478,0.533258,0.294857,0.575478,0.533258,0.294857,0.575478,0.533258,0.294857
recall,1.000000,0.928665,0.897614,1.000000,0.928665,0.897614,1.000000,0.928665,0.897614
f1,0.730544,0.677489,0.443898,0.730544,0.677489,0.443898,0.730544,0.677489,0.443898

In [24]:
plot_df =standard_report
plot_df['model'] = 'standard'
plot_df = pd.concat([plot_df,balanced_report])
plot_df['model'] = plot_df.model.fillna('balanced')
plot_df = pd.concat([plot_df,balanced_param_report])
plot_df['model'] = plot_df.model.fillna('balanced_param')
plot_df.reset_index(inplace=True, names='metric')
plot_df = pd.melt(plot_df, id_vars=['metric', 'model'], value_vars=['train', 'holdout', 'oot'])

## Visualize Performance Comparison

In [25]:
from dash import Dash, dcc, html, Input, Output
from sklearn.model_selection import train_test_split
from sklearn import linear_model, tree, neighbors
from sklearn import metrics, datasets
import plotly.express as px

app = Dash(__name__)

app.layout = html.Div([
    html.H4("Analysis of the ML model's results using scoring metrics"),
    html.P("Select metric:"),
    dcc.Dropdown(
        id='dropdown',
        options=['accuracy', 'precision', 'recall', 'f1'],
        value='precision',
        clearable=False
    ),
    dcc.Graph(id="graph"),
])


@app.callback(
    Output("graph", "figure"), 
    Input('dropdown', "value"))

def train_and_display(metric):


    fig = px.line(plot_df[plot_df.metric==metric], y='value', x='variable', color='model', markers=True)

    return fig


app.run_server(debug=True)

In [26]:
from dash import Dash, dcc, html, Input, Output
from sklearn.model_selection import train_test_split
from sklearn import linear_model, tree, neighbors
from sklearn import metrics, datasets
import plotly.express as px

app = Dash(__name__)
MODELS = {'standard': score_standard_model, 'balanced': score_balanced_model, 'balanced_param': score_balanced_parameter_model}
app.layout = html.Div([
    html.H4("Analysis of the ML model's results using scoring metrics"),
    html.P("Select metric:"),
    dcc.Dropdown(
        id='dropdown',
        options= ['standard', 'balanced', 'balanced_param'],
        value='balanced_param',
        clearable=False
    ),
    dcc.Graph(id="graph"),
])


@app.callback(
    Output("graph", "figure"), 
    Input('dropdown', "value"))

def train_and_display(model):

    return report_class.produce_pr_auc_report(MODELS[model])


app.run_server(debug=True)

## Evaluate on Holdout

In [ ]:
def extract_metrics(results):
    """Extract metrics from cross-validation results.
    
    Args:
        results: List of fold results
        
    Returns:
        DataFrame with metrics
    """
    metrics = []
    for result in results:
        metrics.append({
            'fold': result['fold'],
            'accuracy': result['accuracy']
        })
    return pd.DataFrame(metrics)

# Extract and compare metrics
standard_metrics = extract_metrics(cv_results['standard'])
undersampled_metrics = extract_metrics(cv_results['undersampled'])

print("Standard Sampling Metrics:")
print(standard_metrics.describe())

print("\nUndersampling Metrics:")
print(undersampled_metrics.describe())

## Save Evaluation Results

In [27]:
"""# Combine all evaluation results
evaluation_results = {
    'standard_metrics': standard_metrics.to_dict(),
    'undersampled_metrics': undersampled_metrics.to_dict(),
    'cv_results': cv_results
}

# Save evaluation results
with open('../results/evaluation_results.pkl', 'wb') as f:
    pickle.dump(evaluation_results, f)"""

"# Combine all evaluation results\nevaluation_results = {\n    'standard_metrics': standard_metrics.to_dict(),\n    'undersampled_metrics': undersampled_metrics.to_dict(),\n    'cv_results': cv_results\n}\n\n# Save evaluation results\nwith open('../results/evaluation_results.pkl', 'wb') as f:\n    pickle.dump(evaluation_results, f)"

[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200
[LightGBM] [Warning] min_data_in_leaf is set=200, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=200